usb: gadget: u_ether_ncm: fix missing `struct sk_buff` in tx_complete_ncm_timer
* this is present in the other `tx_complete_ncm_timer` instance and missing in the first,
* so add it into the first and also address "error: use of undeclared identifier 'skb'"

Signed-off-by: SuperAviation001 <superaviation001@gmail.com>